services:
  api:
    container_name: marketplace_api
    build:
      context: .
      dockerfile: Marketplace.Api/Dockerfile
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_URLS=http://+:8080
    env_file:
      - api.env
    depends_on:
      - db
  db:
    container_name: marketplace_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    restart: always
    env_file: db.env
    ports:
      - 2433:1433
    volumes:
      - db-data:/var/opt/mssql/data
      - db-logs:/var/opt/mssql/log
      - db-secrets:/var/opt/mssql/secrets
volumes:
  db-data:
    name: marketplace_db_data
  db-logs:
    name: marketplace_db_logs
  db-secrets:
    name: marketplace_db_secrets
